services:
  api:
    build: .
    image: hello-api:0.1.0
    environment:
      ENV: prod
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  front:
    image: hello-api:0.1.0        
    command: streamlit run front.py --server.port=8501 --server.address=0.0.0.0
    environment:
      BACKEND_BASE: "http://api:8000"   
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "8501:8501"
